apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: jellyfin
  labels:
    app: jellyfin
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      containers:
      - name: jellyfin
        image: jellyfin/jellyfin:latest
        ports:
        - containerPort: 8096
        volumeMounts:
        - name: config-volume
          mountPath: /config
        - name: cache-volume
          mountPath: /cache
        - name: media-volume             # Nuevo volumen para media
          mountPath: /media              # Ruta donde se montará en el contenedor
      volumes:
      - name: config-volume
        persistentVolumeClaim:
          claimName: jellyfin-config-pvc
      - name: cache-volume
        persistentVolumeClaim:
          claimName: jellyfin-cache-pvc
      - name: media-volume              # Declaración del nuevo volumen
        hostPath:
          path: /home/z/diego/jellyfin-kubernetes/media  # Ruta local en tu máquina

