apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-config-pv
  labels:
    app: jellyfin
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home/z/diego/jellyfin-kubernetes/config
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-cache-pv
  labels:
    app: jellyfin
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home/z/diego/jellyfin-kubernetes/cache
